config/routes.rb
Rails.application.routes.draw do
  #test
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :trips do
    resources :accomodations, only: [:index, :new, :create, :destroy]
    resources :participants, only: [:create]
    resources :transportations, only: [:index, :create, :destroy, :update]
    resources :events, only: [:create, :destroy]
    resources :expenses, only: [:index, :update, :show, :destroy, :create]
    resources :messages, only: [:show, :create]
  end

  resources :accomodations, only: [:show, :update] do
    resources :accomodation_votes, only: [:destroy]
  end

  resources :transportations, only: [:show, :update, :index]

  resources :events, only: [:index, :update, :show] do
    resources :event_participants, only: [:create]
  end

  resources :participants, only: [:destroy] do
    resources :accomodations, only: [] do
      resources :accomodation_votes, only: [:new, :create]
    end
  end

  resources :event_participants, only: [:destroy]
  resources :accomodations, only: [] do
    member do
      get :confirm_accomodation
    end
  end

  resources :contacts, only: [:new, :create]
end

app/models/trip.rb
class Trip < ApplicationRecord
  geocoded_by :city
  after_validation :geocode, if: :geocoding_needed?
  has_many :accomodations, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :participants, dependent: :destroy
  has_many :expenses, through: :participants
  validates :start_date, :end_date, :title, presence: true
  validates :title, presence: true, length: { maximum: 25 }
  belongs_to :user
  has_one_attached :photo

  def geocoding_needed?
    will_save_change_to_city? && !will_save_change_to_latitude? && !will_save_change_to_longitude?
  end

  def random_photo
    ["Australia.png", "Egypt.png", "England.png", "Germany.png", "Italy.png", "Pise.png", "Spain.png"].sample
  end
end

app/controllers/trips_controller.rb
require "browser/aliases"
Browser::Base.include(Browser::Aliases)

class TripsController < ApplicationController
  def index
    @user = current_user
    @trip = Trip.new
    @trips = Participant.where(user: @user).map(&:trip)
    @new_participant = Participant.new
    @coming_trips = @trips.select { |trip| trip.start_date > Date.today && trip.end_date > Date.today }
    @past_trips = @trips.select { |trip| trip.start_date < Date.today && trip.end_date < Date.today }
    @current_trips = @trips.select { |trip| trip.start_date <= Date.today && trip.end_date >= Date.today }
    @browser = Browser.new("Some User Agent")
    unless @trips == []
      @markers = @trips.each do |trip|
        if trip.geocoded?
          {
            lat: trip.latitude,
            lng: trip.longitude
          }
        end
      end
    end
  end

  def show
    @trip = Trip.find(params[:id])
    @participants = @trip.participants
    @participant = @participants.find_by(user: current_user)
    if @participant.nil?
      redirect_to trips_path, alert: "Tu ne participes pas à ce voyage"
    else
      # relatif aux transports
      @transportations = @participant.transportations
      @new_transportation = Transportation.new

      # relatif aux accomodations
      @accomodations = @trip.accomodations
      @new_accomodation = Accomodation.new
      if @accomodations.count.positive?
        @markers = @accomodations.geocoded.map do |accomodation|
          {
            lat: accomodation.latitude,
            lng: accomodation.longitude,
            # info_window: render_to_string(partial: "info_window", locals: { accomodations: accomodation }),
            # image_url: helpers.asset_url("emplacement.png")
          }
        end
      end
      @new_accomodation_vote = AccomodationVote.new
      @accomodations.each do |accomodation|
        @accomodation_votes = accomodation.accomodation_votes
      end

      # relatif aux amis
      if params[:query].present?
        sql_query = " \
          users.username ILIKE :query \
          OR users.email ILIKE :query \
        "
        @users = User.where(sql_query, query: "%#{params[:query]}%").reject { |user| user.id == current_user.id }
      end
      @new_participant = Participant.new

      # relatif aux dépenses :
      @mutual_expenses = @trip.expenses.where(mutual: true)
      @individual_expenses = @participant.expenses.where(mutual: false)
      @my_expenses = [@mutual_expenses, @individual_expenses]
      # additionner toutes les dépenses mutuelles :
      @sum_mutual_expenses = @trip.expenses.where(mutual: true).sum(:amount)
      # additionner toutes les dépenses personnelles du participant
      @sum_individual_expenses = @participant.expenses.where(mutual: false).sum(:amount)
      # total par participant
      @total_participant_expenses = @sum_individual_expenses + (@sum_mutual_expenses/@trip.participants.count)
      # créer une nouvelle dépense
      @new_expense = Expense.new

      # relatif aux messages :
      @messages = @trip.messages
      @new_message = Message.new

      # relatifs à l'agenda
      @new_event = Event.new
      @events = @trip.events
      @new_event_participant = EventParticipant.new
      @events.each do |event|
        @event_participants = event.event_participants
      end
    end
  end

  def create
    @new_trip = Trip.new(trip_params)
    @user = current_user
    @new_trip.user = @user
    if @new_trip.save
      @participant = Participant.create!(user: @user, trip: @new_trip)
      redirect_to trip_path(@new_trip), notice: "Cool ! You're ready to plan your holidays "
    else
      render "trips/index", alert: "Your trip couldn't have been created, sorry ! Try again"
    end
  end

  def update
    @trip = Trip.find(params[:id])
    if @trip.update(trip_params)
      redirect_to trip_path
    else
      render "trips/index", alert: "Your trip couldn't have been edited, sorry ! Try again"
    end
  end

  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy
    redirect_to trips_path
  end

  private

  def trip_params
    params.require(:trip).permit(:start_date, :end_date, :title, :description, :city, :photos, :longitude, :latitude)
  end
end

app/views/trips/_modalsTripsIndex.html.erb
<!-- Modal new-->

<div class="modal fade" id="newTrip" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="newTripLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered">
    <div class="modal-content">
      <div class="position-relative" style="z-index: 2;">
        <button type="button" class="btn-close position-absolute" data-bs-dismiss="modal" aria-label="Close" style="top: 15px; right: 15px;"></button>
      </div>
        <div class="modal-body py-5">
          <div class="container">
            <div class="d-flex w-100 align-items-center">
              <h4 class="text-center mb-4 highlight-title mx-auto" id="ModalExpensesCreateLabel">ADD A JOURNEY</h4>
            </div>
          <%= simple_form_for [@user, @trip], url: trips_path, method: :post do |f| %>
            <div class="d-flex justify-content-between">
              <div class="inline-question">
                <%= f.input :title %>
              </div>
              <div class="inline-question">
                  <%= f.input :city,
                  input_html: { data: { geocoder_target: "city" }, placeholder:"Paris, Bordeaux, Londres,..", class: "d-none" },
                  wrapper_html: { data: { controller: "geocoder", geocoder_api_key_value: ENV['MAPBOX_API_KEY'] } } %>
              </div>
            </div>
            <%= f.input :description %>
            <div class="d-flex justify-content-between">
              <div class="inline-question">
              <% if @browser.mobile? %>
                <%= f.input :start_date, as: :date, required: false %>
              <% else %>
                <%= f.input :start_date, as: :string, required: false, input_html: {id: "range_start"} %>
              <% end %>
              </div>
              <div class="inline-question">
              <% if @browser.mobile? %>
                <%= f.input :end_date, as: :date, required: false %>
              <% else %>

              <% end %>
                <%= f.input :end_date, as: :string, required: false, input_html: {id: "range_end"} %>
              </div>
            </div>
            <%= f.input :photo, as: :file%>
            <div class="text-center mt-3">
              <%= f.submit "Start planning!", class: "btn btn-lg btn-homepage" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="currentTrips" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="currentTrips" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered">
    <div class="modal-content">
      <div class="position-relative" style="z-index: 2;">
        <button type="button" class="btn-close position-absolute" data-bs-dismiss="modal" aria-label="Close" style="top: 15px; right: 15px;"></button>
      </div>
      <div class="modal-body py-5">
          <div class="d-flex w-100 align-items-center">
            <h4 class="text-center mb-4 highlight-title mx-auto" id="ModalExpensesCreateLabel">YOUR CURRENT TRIPS</h4>
          </div>
        <div class="tripListModal">
          <% @current_trips.each do |trip| %>
            <% unless trip.photo.attached?%>
              <% trip_photo = "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/beach-quotes-1559667853.jpg"%>
            <% else %>
              <% trip_photo = cloudinary_url trip.photo.key%>
            <% end %>
            <div class="tripCard" style='background-image:linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%=trip_photo%>)'>
              <%= link_to trip_path(trip) do %>
              <div class="tripCardTitle">
                <h1><%= trip.title %></h1>
              </div>
              <div class="tripCardDetails">
                <div class="tripCardDetailsDate">
                  <% unless (trip.start_date.nil? && trip.end_date.nil?) %>
                    <p><%= trip.start_date.strftime("%d/%m/%Y") %> au <%= trip.end_date.strftime("%d/%m/%Y") %></p>
                  <% end %>
                </div>
                <div class="tripCardDetailsTitle">
                  <h1><%= trip.title %></h1>
                </div>
                <div class="tripCardDetailsCity">
                  <% unless trip.city.nil? %>
                    <h4><%= trip.city.gsub(/,.*/,'') %></h4>
                  <% end %>                </div>
                <div class="tripCardDetailsDescription">
                  <p><%= trip.description %></p>
                </div>
              </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/trips/show.html.erb
<div class="dashboardMain">
  <div class="dashboardBox boxInfo">
    <div class="infoDates">
      <% unless @trip.start_date.nil? || @trip.end_date.nil? %>
        <p><%= @trip.start_date.strftime("%d/%m/%Y") %> - <%= @trip.end_date.strftime("%d/%m/%Y") %></p>
      <% end %>
    </div>
    <div class="infoTitle">
      <h1><%= @trip.title %></h1>
    </div>
    <div class="infoDescription">
      <% unless @trip.description.nil? %>
        <p><%= @trip.description %></p>
      <% end %>
    </div>
    <%= image_tag @trip.random_photo, class: "infoPhoto" %>
  </div>
  <div class="dashboardBox boxTransportations">
    <p id="titleCardTransportations">Transports</p>
    <% if @transportations.empty? %>
      <p>Add your ticket !</p>
    <% else %>
      <% @transportations.sort_by(&:departure_date).each do |transportation| %>
        <p>Your next travel to <strong><%= transportation.destination %></strong> is in <%= pluralize ((transportation.departure_date - Time.now)/86400).to_i, "day" %></p>
      <% end %>
    <% end %>
    <% unless @participant.transportations == [] %>
      <button type="button" class="btn btn-light btn-sm btn-more-infos" data-bs-toggle="modal" data-bs-target="#ShowTransportationModal">
        more info
      </button>
    <% end %>
    <button type="button" class="btn btn-add" data-bs-toggle="modal" data-bs-target="#">
      +
    </button>
    <%= render "./trip_boxes/transportations_modal" %>
  </div>
  <div class="dashboardBox boxAccomodations">
    <p id="titleCardAccomodations">Accomodations</p>
    <p>You have <%= pluralize @accomodations.all.count, "accomodation" %> in your wish list.</p>
    <% if @accomodations.empty? %>
      <p>Add one !</p>
    <% else %>
      <% @accomodations.each do |accomodation| %>
        <% if accomodation.confirmed? %>
          <p>Congrats you have chosen your place to stay !</p>
          <%= accomodation.title %>
          <%= accomodation.address %>
        <% end %>
      <% end %>
      <p>Add one or see your wishlist.</p>
    <% end %>
  </div>
  <div class="dashboardBox boxExpenses">
    <p id="titleCardExpenses">Expenses</p>
    <% @my_expenses.flatten.each do |expense| %>
      <%= expense.title %>
      <%= expense.amount %>€
    <% end %>
    <p>Mutual expenses:</p><%= @sum_mutual_expenses %>
  </div>
  <div class="dashboardBox boxPeople">
    <p id="titleCardPeople">Friends</p>
    <% if @participants.count < 2 %>
      <p>You haven't invited anyone yet. Invite some friends!</p>
    <% else %>
      <p>See the list of the friends you're travelling with or add some to your dashboard</p>
      <p>
        <% @trip.participants.each do |participant| %>
          <%= participant.user.email %>
          <%= link_to participant_path(participant), method: :delete, data: { confirm: "Annuler la participation de #{participant.user.username.capitalize} ?" } do %>
            <i class="fas fa-times"></i>
          <% end %>
        <% end %>
      </p>
    <% end %>
  </div>
  <div class="dashboardBox boxEvents">
    <p id="titleCardEvents">Activities</p>
    <% if @events.empty? %>
      <p>You haven't planned anything yet. Start !</p>
    <% else %>
      <% @events.each do |event| %>
        <%= event.description %>
        <%= event.category %>
        <p><%= event.start_date.strftime("%d/%m/%Y") %> à <%= event.start_date.strftime("%H:%M") %></p>
      <% end %>
    <% end %>
  </div>
  <div class="dashboardBox boxPhotos">
    <% if @trip.photo.attached? %>
      <p>Afficher les photos lol</p>
      <p>See the photos</p>
    <% else %>
      <p>Add some photos </p>
    <% end %>
  </div>
</div>

<div class="container">
  <h1>Form new transportation</h1>
  <%= simple_form_for [@trip, @new_transportation] do |f| %>
    <%= f.input :origin, placeholder:"Paris, Gare de Lyon,...", label:"From..." %>
    <%= f.input :destination, placeholder:"Madrid, London Heathrow,...", label:"To..." %>
    <%= f.input :departure_date, label:"When are you leaving?", as: :string, required: false, input_html: {id: "range_start_2"}, placeholder:"21/03/2022"%>
    <%= f.input :arrival_date, label:"When are you arriving?", as: :string, required: false, input_html: {id: "range_end_2"}, placeholder:"21/03/2022"%>
    <%= f.input :mean, label:"Avion, train, voiture?", as: :select, collection: Transportation::CATEGORIES %>
    <%= f.input :price, label:"Prix", placeholder:"100 €" %>
    <%= f.submit "Let's go" %>
  <% end %>
  <p>Form marche</p>
</div>

<div class="container">
  <h1>Show/index transportations</h1>
  <% if @transportations.count > 0 %>
    <% @transportations.order('departure_date ASC').each do |transportation|  %>
      <div class="transportation-ticket col">
        <div class="row">
          <p>Departure:  <%= transportation.departure_date.strftime("%A") %> <%= transportation.departure_date.month %>, <%= transportation.departure_date.day %>, <%= transportation.departure_date.year %> at <%= transportation.departure_date.hour %> :
          <% if transportation.departure_date.min == 0 %>
            00
          <% else %>
            <%= transportation.departure_date.min %>
          <% end %>
          </p>
        </div>
        <div class="row">
          <p><%= transportation.origin %> to <%= transportation.destination %></p>
        </div>
        <div class="row">
          <p>Duration: <%= ((transportation.arrival_date - transportation.departure_date)/3600).round %>h</p>
        </div>
        <div class="row">
      <%= link_to trip_transportation_path(transportation.participant.trip, transportation), method: :delete, data: { confirm: "Supprimer le billet ?" } do %>
        <i class="fas fa-times"></i>
      <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<div class="container">
  <h1>Form new accomodation</h1>
  <%= simple_form_for [@trip, @new_accomodation] do |f| %>
    <%= f.input :title, placeholder: "Family house", label: "Titre du logement" %>
    <%= f.input :address,
      placeholder: "88 rue de Rivoli",
      label: "Adresse",
      input_html: { data: { geocoder_target: "address" } },
      wrapper_html: { data: { geocoder_target: "addressWrapper" }},
      label: "Address" %>
    <%= f.input :price, placeholder: "300 €", label: "Prix"  %>
    <%= f.input :latitude, as: :hidden, input_html: { data: { geocoder_target: "latitude" }} %>
    <%= f.input :longitude, as: :hidden, input_html: { data: { geocoder_target: "longitude" }} %>
    <%= f.input :img, placeholder:"https://www.familyhouse.com/.jpeg", label: "Lien de l'image" %>
    <%= f.input :description, placeholder: "Perfect house for families", label: "Description" %>
    <%= f.input :url, placeholder: "https://www.airbnb.fr/rooms/604726298950758799?adults=1&category_tag=...", label: "Lien du logement" %>
    <%= f.submit "Let's go" %>
  <% end %>
</div>

<div class="container" data-controller="accomodation-infos">
  <h1>Index accomodations</h1>
  <% if @accomodations.count.positive? %>
    <div>
      <% @accomodations.each do |accomodation|  %>
        <div>
          <p>Title: <%= accomodation.title %></p>
          <p>Address : <%= accomodation.address %></p>
          <%= link_to trip_accomodation_path(accomodation.trip, accomodation), method: :delete, data: { confirm: "Supprimer le logement ?" } do %>
            <i class="fas fa-times"></i>
          <% end %>
          <button data-action="click->accomodation-infos#revealContent" data-accomodation-infos-target="button1">Voir + </button>
          <button data-action="click->accomodation-infos#hideContent" data-accomodation-infos-target="button2" class="d-none">Voir -</button>
          <div class="d-none" data-accomodation-infos-target="content">
            <p>Description : <%= accomodation.description %></p>
            <p>Lien: <%= accomodation.url %></p>
            <p>Nombre de votes: <%=  accomodation.accomodation_votes.count %></p>
            <% if @participant.votes?(accomodation) %>
              <%= link_to accomodation_accomodation_vote_path(AccomodationVote.find_by(participant: @participant, accomodation: accomodation)), class: "d-flex align-items-center fav-button", method: :delete, data: { confirm: "Annuler le vote ?" } do %>
                <p>Supprimer le vote</p>
              <% end %>
            <% else %>
              <%= link_to participant_accomodation_accomodation_votes_path(@participant, accomodation, @new_accomodation_vote), method: :post do %>
                <p>Vote</p>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
  <div class="d-flex align-items-center justify-content-center pb-4" data-accomodation-infos-target="accomodationsMap">
    <div style="width:50%; height:100px"
      data-controller="mapbox"
      data-mapbox-markers-value="<%= @markers.to_json %>"
      data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

<div class="container">
  <h1>Form new event</h1>
  <%= simple_form_for [@trip, @new_event] do |f| %>
    <%= f.input :description, placeholder: "Cooking class,...", label: "Name" %>
    <%= f.input :start_date, as: :string, required: false, input_html: {id: "range_start_3"}, placeholder:"21/03/2022 at 09:00AM", label: "Starts when?" %>
    <%= f.input :end_date, as: :string, required: false, input_html: {id: "range_end_3"}, placeholder:"21/03/2022 at 09:00AM", label: "Ends when?" %>
    <%= f.input :category, as: :select, collection: Event::ACTIVITIES%>
    <%= f.submit "Let's go" %>
  <% end %>
</div>

<div class="container">
  <h1>Index events</h1>
  <% if @events.count > 0 %>
    <% @events.each do |event|  %>
      <p>Date: <%= event.start_date %></p>
      <p>Category : <%= event.category %></p>
      <p>Description : <%= event.description %></p>
      <p>Who is coming?
        <% event.event_participants.each do |event_participant| %>
          <%=  event_participant.participant.user.email %>
        <% end %>
      </p>
      <%= link_to trip_event_path(event.trip, event), method: :delete, data: { confirm: "Supprimer l'évènement du calendrier ?" } do %>
        <i class="fas fa-times"></i>
      <% end %>
      <% if @participant.participates?(event) %>
        <%= link_to event_participant_path(event.event_participants.find_by(participant_id: @participant.id)), method: :delete, data: { confirm: "Ne plus participer ?" } do %>
          <i class="fas fa-times-circle delete-event-participant"></i>
        <% end %>
      <% else %>
        <%= simple_form_for [event, @new_event_participant] do |f|%>
          <%= button_tag type: 'submit' do %>
            <div aria-hidden="true">Participate</div>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</div>

<div class="container">
  <h1>Form new expense</h1>
  <%= simple_form_for [@trip, @new_expense] do |f| %>
    <%= f.input :title, placeholder: "Location, Billet,...", label: "Titre de la dépense" %>
    <%= f.input :amount, as: :float, placeholder: "20€", label: "Montant" %>
    <%= f.input :mutual, as: :boolean, input_html: { class: "toggle", value: true }, label:"Tick this box if the purchase was for everyone" %>
    <%= f.input :expense_date, as: :string, required: false, input_html: {class: "datepicker"}, placeholder:"21/03/2022", label: "Jour de la dépense"%>
    <%= f.submit "Ajouter une dépense" %>
  <% end %>
</div>


<div class="container">
  <h1>Index expenses</h1>
  <% if @my_expenses.flatten.count > 0 %>
    <% @my_expenses.flatten.each do |expense|  %>
      <p>Titre: <%= expense.title %></p>
      <%= link_to trip_expense_path(@trip, expense), method: :delete, data: { confirm: "Supprimer la dépense ?" } do %>
        <i class="fas fa-times"></i>
      <% end %>
    <% end %>
  <% end %>
</div>

<div class="container">
  <% unless @my_expenses.count.zero? %>
    <%= pie_chart [["Individual", @sum_individual_expenses], ["Mutual", @sum_mutual_expenses/@trip.participants.count]], legend: false  %>
  <% end %>
</div>

<div class="container">
  <h1>Index users & form new_participant</h1>
  <%= form_tag trip_path, method: :get, class: "d-flex" do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Trouve un user avec son email"
    %>
    <%= submit_tag "Search", class: "btn btn-primary" %>
  <% end %>
  <% if !@users.nil? %>
    <% @users.each do |user| %>
      <%= user.email %>
      <%= simple_form_for [@trip, @new_participant] do |f| %>
        <%= f.input :user_id, as: :hidden, input_html: {value: user.id}%>
        <%= f.input :trip_id, as: :hidden, input_html: {value: @trip.id} %>
        <%= f.submit "Ajouter qn" %>
      <% end %>
    <% end %>
  <% elsif @users == [] %>
    <p>Désolés mais ta recherche n'a rien donné...</p>
  <% end %>
</div>

<div
  class="container"
  style="margin-top:30px"
  data-controller="trip-subscription" data-trip-subscription-current-user-id-value="<%= current_user.id %>" data-trip-subscription-trip-id-value="<%= @trip.id %>">
  <div
    class="messages"
    style="width:100%; height:200px" data-trip-subscription-target="messages">
    <% @messages.each do |message| %>
      <div id="message-<%= message.id %>">
        <%= render "messages/message", message: message %>
      </div>
    <% end %>
  </div>
  <%= simple_form_for [@trip, @new_message],
    remote: true,
    html: {
      # class: "d-flex",
      'data-trip-subscription-target': 'form'
      } do |f| %>
      <%= f.input :content %>
      <%= f.submit "Send", class: "btn btn-primary" %>
  <% end %>
</div>