config/routes.rb
Rails.application.routes.draw do
  #test
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :trips do
    resources :accomodations, only: [:index, :new, :create, :destroy]
    resources :participants, only: [:create]
    resources :transportations, only: [:index, :create, :destroy, :update]
    resources :events, only: [:create, :destroy]
    resources :expenses, only: [:index, :update, :show, :destroy, :create]
    resources :messages, only: [:show, :create]
  end

  resources :accomodations, only: [:show, :update] do
    resources :accomodation_votes, only: [:destroy]
  end

  resources :transportations, only: [:show, :update, :index]

  resources :events, only: [:index, :update, :show] do
    resources :event_participants, only: [:create]
  end

  resources :participants, only: [:destroy] do
    resources :accomodations, only: [] do
      resources :accomodation_votes, only: [:new, :create]
    end
  end

  resources :event_participants, only: [:destroy]
  resources :accomodations, only: [] do
    member do
      get :confirm_accomodation
    end
  end

  resources :contacts, only: [:new, :create]
end

app/views/shared/_avatar.html.erb
  <div>
    <% unless user_signed_in? %>
      <%= image_tag "https://res.cloudinary.com/dyqby7tbh/image/upload/v1646667807/placeholder_user_f6tjii.png", class:"avatar", id:"navbarDarkDropdown",
      data: { bs_toggle: "dropdown"}, aria:{ haspopup:true, expanded:false } %>
    <% else %>
      <%= image_tag "https://res.cloudinary.com/dyqby7tbh/image/upload/v1646667807/placeholder_user_f6tjii.png", class:"avatar", id:"navbarDropdown", aria:{ haspopup:true, expanded:false }, data: { bs_toggle: "dropdown"} %>
    <% end %>
    <div class="dropdown-menu dropdown-menu-end dropdown-menu-light" id="dropdown-menu-avatar" aria-labelledby="navbarDropdown">
        <% unless user_signed_in? %>
          <%= link_to "Sign in", new_user_session_path, class:"dropdown-item", id:"dropdown-item-avatar"%>
        <% else %>
          <%= link_to "My trips", trips_path, class: "dropdown-item", id:"dropdown-item-avatar" %>
          <a type="button" class="dropdown-item" id="dropdown-item-avatar" data-bs-toggle="modal" data-bs-target="#newTrip">
            New trip ...
          </a>
          <%= link_to "Edit account", edit_user_registration_path, class:"dropdown-item", id:"dropdown-item-avatar" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class:"dropdown-item", id:"dropdown-item-avatar" %>
        <% end%>
    </div>
  </div>

app/views/shared/_cookies_bar.html.erb
<div id="cookies-bar" class="cookies-bar">
  <p>
    We use cookies. Do you accept them?
  </p>

  <%= link_to 'Accept', request.original_url, class: 'btn accept' %>
  <%= link_to 'Reject', request.original_url, class: 'btn reject' %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-transparent">
  <div class="container-fluid">
    <%= link_to root_path do%>
      <%= image_tag "Logo.png", style: "height: 50px;" %>
    <% end %>
    <div class="d-flex">
      <% if user_signed_in? %>
        <%= link_to "My trips", trips_path, class: "btn", id: "my-trips-btn" %>
      <% end %>
      <%= render 'shared/avatar' %>
    </div>
  </div>
</nav>

app/views/shared/_timeline.html.erb
<%# TIMELINE %>
<div class="home-timeline">
  <div class="d-flex justify-content-center m-5">
    <h1 id="timeline-title">How it works</h1>
  </div>

  <div class="container">
    <%# TIMELINE ROW 1 %>
    <div class="row timeline-row">
      <div class="col content-timeline-left">
        <h3>Sign up</h3>
        <p>Create an account to join the <strong>Momenters community</strong></p>
      </div>
      <div class="col timeline-card-arrow">
          <div class="timeline-div-arrow-left">
            <div class="div-arrow-rounded">
              <%= image_tag "right-arrow.png", alt: "arrow", width: 20, height: 20 %>
            </div>
          </div>
          <div class="card-timeline">
            <div class="number-card-timeline">
              <h3>1</h3>
            </div>
            <div class="card-timeline-infos">
              <%= image_tag "signup.png", alt: "Sign up", width: 75, height: 75 %>
            </div>
          </div>
      </div>
    </div>

    <%# TIMELINE ROW 2 %>
    <div class="row timeline-row">
      <div class="col timeline-card-arrow">
          <div class="card-timeline">
            <div class="number-card-timeline">
              <h3>2</h3>
            </div>
           <div class="card-timeline-infos">
              <%= image_tag "promotion.png", alt: "Promotion", width: 75, height: 75 %>
            </div>
          </div>
          <div class="timeline-div-arrow-right">
            <div class="div-arrow-rounded-right">
             <%= image_tag "right-arrow.png", alt: "arrow", width: 20, height: 20 %>
            </div>
          </div>
      </div>
      <div class="col content-timeline-right">
        <div class="ps-5">
          <h3>Invite your friends</h3>
          <p>Get the <strong>ones you love</strong> and you want to spend time with</p>
        </div>
      </div>
    </div>

    <%# TIMELINE ROW 3 %>
    <div class="row timeline-row">
      <div class="col content-timeline-left">
        <h3>Plan ahead</h3>
        <p>Create your <strong>first Moment</strong> and plan everything in one place so you can focus on enjoying with your friends</p>
      </div>
      <div class="col timeline-card-arrow">
          <div class="timeline-div-arrow-left">
            <div class="div-arrow-rounded">
              <%= image_tag "right-arrow.png", alt: "arrow", width: 20, height: 20 %>
            </div>
          </div>
          <div class="card-timeline">
            <div class="number-card-timeline">
              <h3>3</h3>
            </div>
            <div class="card-timeline-infos">
              <%= image_tag "check-mark.png", alt: "Plan ahead", width: 75, height: 75 %>
            </div>
          </div>
      </div>
    </div>

    <%# TIMELINE ROW 4 %>
    <div class="row timeline-row">
      <div class="col timeline-card-arrow">
          <div class="card-timeline">
            <div class="number-card-timeline">
              <h3>4</h3>
            </div>
           <div class="card-timeline-infos">
              <%= image_tag "camera.png", alt: "Create Memories", width: 75, height: 75 %>
            </div>
          </div>
          <div class="timeline-div-arrow-right">
            <div class="div-arrow-rounded-right">
             <%= image_tag "right-arrow.png", alt: "arrow", width: 20, height: 20 %>
            </div>
          </div>
      </div>
      <div class="col content-timeline-right">
        <div class="ps-5">
          <h3>Create friends</h3>
          <p>Keep tracks of <strong> all yours trips </strong> (photos, activities) in one place </p>
        </div>
      </div>
    </div>

    <%# TIMELINE ROW 5 %>
    <div class="row timeline-row">
      <div class="col content-timeline-left">
        <h3>Shared with your <br> loved ones</h3>
        <p>Share your memories <strong>easily on social networks</strong> with auto-edited content</p>
      </div>
      <div class="col timeline-card-arrow">
          <div class="timeline-div-arrow-left">
            <div class="div-arrow-rounded">
              <%= image_tag "right-arrow.png", alt: "arrow", width: 20, height: 20 %>
            </div>
          </div>
          <div class="card-timeline">
            <div class="number-card-timeline">
              <h3>5</h3>
            </div>
            <div class="card-timeline-infos">
              <%= image_tag "online-match.png", alt: "Shared", width: 75, height: 75 %>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>
<%# END TIMELINE %>

app/views/shared/_transportations.html.erb
<%= simple_form_for [@participant, @new_transportation] do |f| %>
  <%= f.input :origin, placeholder:"Paris, Gare de Lyon,...", label:"From..." %>
  <%= f.input :destination, placeholder:"Madrid, London Heathrow,...", label:"To..." %>
  <%= f.input :departure_date, label:"Departure" %>
  <%= f.input :arrival_date, label:"Arrival" %>
  <%= f.input :mean, label:"Avion, train, voiture?", as: :select, collection: Transportation::CATEGORIES %>
  <%= f.input :price, label:"Prix", placeholder:"100 €" %>
  <%= f.submit "Let's go" %>
<% end %>

<%# <%= simple_form_for [@transportations.first] do |f| %>
  <%# <%= f.input :origin, placeholder:"Paris, Gare de Lyon,...", label:"From..." %> %>
  <%# <%= f.input :destination, placeholder:"Madrid, London Heathrow,...", label:"To..." %> %>
  <%# <%= f.input :departure_date, label:"Departure" %> %>
  <%# <%= f.input :arrival_date, label:"Arrival" %> %>
  <%# <%= f.input :mean, label:"Avion, train, voiture?", as: :select, collection: Transportation::CATEGORIES %> %>
  <%# <%= f.input :price, label:"Prix", placeholder:"100 €" %> %>
  <%# <%= f.submit "Let's go" %> %>
<%# <% end %> %> %>